/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package sample

import com.beust.klaxon.Klaxon

fun main() {

        val student = Klaxon()
            .parse < Person > (""" 
                {
                    "name": "John Smith",
                    "age": 23
                }
                """)

                print(student?.name)
            }
class Person(val name: String, val age: Int)